- name: Install Packages dependencies.
  apt: 
    name: "{{ item.package_name }}"
    state: "{{ item.package_state }}"
  loop: "{{ packages }}"

- name: Install AWS CLI
  ansible.builtin.shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install


- name: Install kubectl
  ansible.builtin.shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
    echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: Install Helm
  ansible.builtin.shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh

- name: Create AWS Directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.type }}"
  loop: "{{ create_dir }}"

- name: Copy AWS configuration Files
  template:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop: "{{ templates }}"

- name: Edit file permission
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "{{ item.mode }}"
  loop: "{{ file_permission }}"

- name: Update Kubeconfig
  ansible.builtin.shell: ".aws/kubeconfig.sh"
  become: false
