kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-jenkins
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/log"